---
name: Benchmark CLI

on: repository_dispatch

jobs:
  build:
    name: Benchmark CLI

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        node-version: [10.x, 12.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
        with:
          path: ${{ env.RUNNER_WORKSPACE }}
      - uses: actions/checkout@v1
        with:
          repository: ${{ github.event.client_payload.owner }}/${{ github.event.client_payload.repo }}
          ref: ${{ github.event.client_payload.commit_sha }}
          fetch-depth: 1
          token: ${{ secrets.NPM_DEPLOY_USER_PAT }}
          path: ${{ env.RUNNER_WORKSPACE }}
      - name: use nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-verison }}
      - name: Env
        run: |
          set -x
          echo "${GITHUB_WORKSPACE}"
          pwd
          ls -al .
          ls -al ..
          echo "${{ toJson(github.event) }}"
          printenv
