---
name: Benchmark CLI

on: repository_dispatch

jobs:
  benchmark:
    name: Benchmark CLI

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        node-version: [10.x, 12.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout/benchmarks
        uses: actions/checkout@v1
        with:
          path: ${{ env.RUNNER_WORKSPACE }}
      - name: checkout/${{ github.event.client_payload.owner }}/${{ github.event.client_payload.repo }}
        uses: actions/checkout@v1
        with:
          repository: ${{ github.event.client_payload.owner }}/${{ github.event.client_payload.repo }}
          ref: ${{ github.event.client_payload.commit_sha }}
          fetch-depth: 1
          token: ${{ secrets.NPM_DEPLOY_USER_PAT }}
          path: ${{ env.RUNNER_WORKSPACE }}
      - name: use nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-verison }}

      - name: Install benchmark deps
        run: |
          cd "${GITHUB_WORKSPACE}"
          npm install --production

      - name: Unlink npm/cli
        if: github.event.client_payload.repo == 'cli'
        run: |
          cd "${RUNNER_WORKSPACE}/${{ github.event.client_payload.repo }}"
          pwd
          sudo node bin/npm-cli.js rm npm -g -f

      - name: Globally link npm/cli
        if: github.event.client_payload.repo == 'cli'
        run: |
          cd "${RUNNER_WORKSPACE}/${{ github.event.client_payload.repo }}"
          pwd
          sudo node bin/npm-cli.js link -f

      - name: Validate link npm/cli
        if: github.event.client_payload.repo == 'cli'
        run: |
          cd "${RUNNER_WORKSPACE}/${{ github.event.client_payload.repo }}"
          pwd
          echo "Command Path: $(which npm)"
          echo "Global node_modules: "
          ls -l "$(dirname $(which npm))/../lib/node_modules"
          echo "PWD: $(pwd)"
          echo "Current Commit: $(git log --oneline -1)"

      - name: Run Benchmark
        run: |
          echo "Running benchmark..."
          echo "PWD: $(pwd)"

      - name: Post to Pull-Request
        # if: contains(github.event.action, 'pull_request')
        if: github.event.action == 'pull_request'
        run: echo "Posting to pull-request..."

      - name: Commit Results
        # if: contains(github.event.action, 'push')
        if: github.event.action == 'push'
        run: echo "Committing results..."

      # TODO: remove this step
      - name: Env
        run: |
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "PWD: $(pwd)"
          ls -al .
          ls -al ..
          echo "${{ toJson(github.event) }}"
          printenv
