---
name: Benchmark (Manual)
on:
  workflow_dispatch:
    inputs:
      managers:
        description: 'Comma separated list of package managers to benchmark'
        required: true
        default: 'all'
      benchmarks:
        description: 'Command separated list of benchmarks to be executed'
        required: true
        default: 'all'
      fixtures:
        description: 'Comma separated list of fixtures to benchmark against'
        required: true
        default: 'all'
jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: ./benchmark.sh -m ${{ inputs.managers }} -b ${{ inputs.benchmarks }} -f ${{ inputs.fixtures }}
        shell: bash
